- name: install supervisord
  yum: name=supervisor state=present

- name: Configure supervisord file
  template: src=supervisord.conf.j2 dest=/etc/supervisord.conf

- name: Start the supervisord service
  service: name=supervisord state=started enabled=yes